export const shops = [
  { id: "rewe", name: "REWE", short: "R", kind: "Supermarkt", color: "#cc1838", soft: "#fff0f2", homepage: "https://www.rewe.de" },
  { id: "lidl", name: "Lidl", short: "Li", kind: "Discounter", color: "#0753a6", soft: "#eef6ff", homepage: "https://www.lidl.de" },
  { id: "aldi", name: "ALDI", short: "A", kind: "Discounter", color: "#0871b9", soft: "#edf8ff", homepage: "https://www.aldi-nord.de" },
  { id: "edeka", name: "EDEKA", short: "E", kind: "Supermarkt", color: "#f2b400", soft: "#fff9de", homepage: "https://www.edeka.de" },
  { id: "kaufland", name: "Kaufland", short: "K", kind: "Supermarkt", color: "#d51b30", soft: "#fff0f1", homepage: "https://www.kaufland.de" },
  { id: "penny", name: "PENNY", short: "P", kind: "Discounter", color: "#d71920", soft: "#fff1ef", homepage: "https://www.penny.de" },
  { id: "netto", name: "Netto", short: "N", kind: "Discounter", color: "#f5c800", soft: "#fff9d6", homepage: "https://www.netto-online.de" },
  { id: "dm", name: "dm", short: "dm", kind: "Drogerie", color: "#cc1c4a", soft: "#fff0f4", homepage: "https://www.dm.de" },
  { id: "rossmann", name: "Rossmann", short: "Ro", kind: "Drogerie", color: "#b41f2e", soft: "#fff1f2", homepage: "https://www.rossmann.de" },
  { id: "amazon", name: "Amazon", short: "a", kind: "Online", color: "#1f2933", soft: "#f2f3f4", homepage: "https://www.amazon.de" },
  { id: "otto", name: "OTTO", short: "O", kind: "Online", color: "#e30613", soft: "#fff0f1", homepage: "https://www.otto.de" },
  { id: "mediamarkt", name: "MediaMarkt", short: "M", kind: "Technik", color: "#d71920", soft: "#fff1ef", homepage: "https://www.mediamarkt.de" },
  { id: "ikea", name: "IKEA", short: "I", kind: "Wohnen", color: "#075aa3", soft: "#eef6ff", homepage: "https://www.ikea.com/de/de/" },
  { id: "zalando", name: "Zalando", short: "Z", kind: "Mode", color: "#ed6b22", soft: "#fff3eb", homepage: "https://www.zalando.de" }
];

export const categories = ["Alle", "Lebensmittel", "Drogerie", "Haushalt", "Technik", "Wohnen", "Mode"];

export const products = [
  {
    id: "dm-haferdrink-natur",
    shopId: "dm",
    name: "dmBio Haferdrink Natur",
    subtitle: "1 l · vegan · Bio",
    category: "Lebensmittel",
    priceCents: 90,
    unit: "0,90 € / l",
    emoji: "🥛",
    tone: "oat",
    verified: true,
    checkedAt: "14.08.2026",
    sourceUrl: "https://www.dm.de/p/d/1453941/dmbio-pflanzendrink-haferdrink-natur",
    highlight: "Dauerpreis"
  },
  {
    id: "dm-haferdrink-barista",
    shopId: "dm",
    name: "dmBio Haferdrink Barista",
    subtitle: "1 l · aufschäumbar",
    category: "Lebensmittel",
    priceCents: 145,
    unit: "1,45 € / l",
    emoji: "☕",
    tone: "coffee",
    verified: true,
    checkedAt: "14.08.2026",
    sourceUrl: "https://www.dm.de/tipps-und-trends/nachhaltigkeit/bio-lebensmittel/bio-milch-693992",
    highlight: "Beliebt"
  },
  {
    id: "dm-haferflocken-fein",
    shopId: "dm",
    name: "dmBio Haferflocken Feinblatt",
    subtitle: "1 kg · Bio",
    category: "Lebensmittel",
    priceCents: 155,
    unit: "1,55 € / kg",
    emoji: "🌾",
    tone: "grain",
    verified: true,
    checkedAt: "14.08.2026",
    sourceUrl: "https://www.dm.de/tipps-und-trends/rezepte/hafermilch-selber-machen-2048142",
    highlight: "Vorrat"
  },
  {
    id: "dm-haferflocken-gross",
    shopId: "dm",
    name: "dmBio Haferflocken Großblatt",
    subtitle: "500 g · Bio",
    category: "Lebensmittel",
    priceCents: 85,
    unit: "1,70 € / kg",
    emoji: "🥣",
    tone: "grain",
    verified: true,
    checkedAt: "14.08.2026",
    sourceUrl: "https://www.dm.de/tipps-und-trends/rezepte/hafermilch-selber-machen-2048142"
  },
  {
    id: "dm-schokotropfen",
    shopId: "dm",
    name: "dmBio Schokotropfen Zartbitter",
    subtitle: "100 g · backfest",
    category: "Lebensmittel",
    priceCents: 175,
    unit: "17,50 € / kg",
    emoji: "🍫",
    tone: "cocoa",
    verified: true,
    checkedAt: "14.08.2026",
    sourceUrl: "https://www.dm.de/tipps-und-trends/rezepte/coffee-porridge-832874"
  },
  {
    id: "dm-milch-laktosefrei",
    shopId: "dm",
    name: "Berchtesgadener H-Milch",
    subtitle: "1 l · 1,5 % · laktosefrei",
    category: "Lebensmittel",
    priceCents: 165,
    unit: "1,65 € / l",
    emoji: "🐄",
    tone: "sky",
    verified: true,
    checkedAt: "14.08.2026",
    sourceUrl: "https://www.dm.de/tipps-und-trends/nachhaltigkeit/bio-lebensmittel/bio-milch-693992"
  },
  {
    id: "rewe-bio-milch",
    shopId: "rewe",
    name: "REWE Bio H-Milch",
    subtitle: "1 l · 1,5 % Fett",
    category: "Lebensmittel",
    priceCents: 129,
    unit: "Demo · regional",
    emoji: "🥛",
    tone: "sky",
    verified: false,
    sourceUrl: "https://shop.rewe.de/c/milch/",
    highlight: "Regional"
  },
  {
    id: "rewe-bananen",
    shopId: "rewe",
    name: "Bananen",
    subtitle: "ca. 1 kg · lose",
    category: "Lebensmittel",
    priceCents: 199,
    unit: "Demo · regional",
    emoji: "🍌",
    tone: "banana",
    verified: false
  },
  {
    id: "rewe-pasta",
    shopId: "rewe",
    name: "Penne Rigate",
    subtitle: "500 g · Hartweizen",
    category: "Lebensmittel",
    priceCents: 99,
    unit: "Demo · regional",
    emoji: "🍝",
    tone: "grain",
    verified: false
  },
  {
    id: "lidl-tomaten",
    shopId: "lidl",
    name: "Bio Rispentomaten",
    subtitle: "500 g · Klasse I",
    category: "Lebensmittel",
    priceCents: 249,
    unit: "Demo · Prospektfeed offen",
    emoji: "🍅",
    tone: "tomato",
    verified: false,
    highlight: "Angebot"
  },
  {
    id: "lidl-brot",
    shopId: "lidl",
    name: "Mehrkornbrot",
    subtitle: "750 g · frisch gebacken",
    category: "Lebensmittel",
    priceCents: 179,
    unit: "Demo · Prospektfeed offen",
    emoji: "🍞",
    tone: "bread",
    verified: false
  },
  {
    id: "aldi-apfelsaft",
    shopId: "aldi",
    name: "Naturtrüber Apfelsaft",
    subtitle: "1 l · Direktsaft",
    category: "Lebensmittel",
    priceCents: 149,
    unit: "Demo · Prospektfeed offen",
    emoji: "🍎",
    tone: "apple",
    verified: false
  },
  {
    id: "aldi-eier",
    shopId: "aldi",
    name: "Bio Eier",
    subtitle: "6 Stück · Größe M/L",
    category: "Lebensmittel",
    priceCents: 299,
    unit: "Demo · Prospektfeed offen",
    emoji: "🥚",
    tone: "oat",
    verified: false
  },
  {
    id: "edeka-butter",
    shopId: "edeka",
    name: "Deutsche Markenbutter",
    subtitle: "250 g · mildgesäuert",
    category: "Lebensmittel",
    priceCents: 229,
    unit: "Demo · regional",
    emoji: "🧈",
    tone: "banana",
    verified: false
  },
  {
    id: "edeka-avocado",
    shopId: "edeka",
    name: "Avocado Hass",
    subtitle: "1 Stück · essreif",
    category: "Lebensmittel",
    priceCents: 149,
    unit: "Demo · regional",
    emoji: "🥑",
    tone: "leaf",
    verified: false
  },
  {
    id: "kaufland-reis",
    shopId: "kaufland",
    name: "Basmati Reis",
    subtitle: "1 kg · aromatisch",
    category: "Lebensmittel",
    priceCents: 299,
    unit: "Demo · Anbindung offen",
    emoji: "🍚",
    tone: "oat",
    verified: false
  },
  {
    id: "penny-kaese",
    shopId: "penny",
    name: "Gouda Jung",
    subtitle: "400 g · in Scheiben",
    category: "Lebensmittel",
    priceCents: 279,
    unit: "Demo · Prospektfeed offen",
    emoji: "🧀",
    tone: "banana",
    verified: false
  },
  {
    id: "netto-kaffee",
    shopId: "netto",
    name: "Caffè Crema Bohnen",
    subtitle: "1 kg · ganze Bohne",
    category: "Lebensmittel",
    priceCents: 1099,
    unit: "Demo · Prospektfeed offen",
    emoji: "☕",
    tone: "coffee",
    verified: false,
    highlight: "Top Deal"
  },
  {
    id: "rossmann-shampoo",
    shopId: "rossmann",
    name: "Repair Shampoo",
    subtitle: "300 ml · trockenes Haar",
    category: "Drogerie",
    priceCents: 149,
    unit: "Demo · Shopfeed offen",
    emoji: "🧴",
    tone: "lavender",
    verified: false
  },
  {
    id: "rossmann-waschmittel",
    shopId: "rossmann",
    name: "Colorwaschmittel",
    subtitle: "20 Waschladungen",
    category: "Haushalt",
    priceCents: 495,
    unit: "Demo · Shopfeed offen",
    emoji: "🫧",
    tone: "sky",
    verified: false
  },
  {
    id: "amazon-kabel",
    shopId: "amazon",
    name: "USB-C Ladekabel",
    subtitle: "2 m · geflochten",
    category: "Technik",
    priceCents: 899,
    unit: "Demo · Partner-API offen",
    emoji: "🔌",
    tone: "graphite",
    verified: false,
    highlight: "Online"
  },
  {
    id: "amazon-dosen",
    shopId: "amazon",
    name: "Vorratsdosen Set",
    subtitle: "5-teilig · BPA-frei",
    category: "Haushalt",
    priceCents: 2499,
    unit: "Demo · Partner-API offen",
    emoji: "🫙",
    tone: "mint",
    verified: false
  },
  {
    id: "otto-handtuecher",
    shopId: "otto",
    name: "Handtuch-Set",
    subtitle: "6-teilig · Baumwolle",
    category: "Wohnen",
    priceCents: 2999,
    unit: "Demo · Partnerfeed offen",
    emoji: "🧺",
    tone: "lavender",
    verified: false
  },
  {
    id: "mediamarkt-kopfhoerer",
    shopId: "mediamarkt",
    name: "Bluetooth Kopfhörer",
    subtitle: "Over-Ear · 40 h Akku",
    category: "Technik",
    priceCents: 4999,
    unit: "Demo · Partnerfeed offen",
    emoji: "🎧",
    tone: "graphite",
    verified: false,
    highlight: "Online"
  },
  {
    id: "mediamarkt-powerbank",
    shopId: "mediamarkt",
    name: "Powerbank 10.000 mAh",
    subtitle: "USB-C · Schnellladen",
    category: "Technik",
    priceCents: 2499,
    unit: "Demo · Partnerfeed offen",
    emoji: "🔋",
    tone: "mint",
    verified: false
  },
  {
    id: "ikea-lampe",
    shopId: "ikea",
    name: "Tischleuchte",
    subtitle: "warmweiß · 28 cm",
    category: "Wohnen",
    priceCents: 1499,
    unit: "Demo · Partnerfeed offen",
    emoji: "💡",
    tone: "banana",
    verified: false
  },
  {
    id: "ikea-decke",
    shopId: "ikea",
    name: "Wolldecke",
    subtitle: "130 × 170 cm",
    category: "Wohnen",
    priceCents: 999,
    unit: "Demo · Partnerfeed offen",
    emoji: "🛋️",
    tone: "rose",
    verified: false
  },
  {
    id: "zalando-sneaker",
    shopId: "zalando",
    name: "Alltags-Sneaker",
    subtitle: "Unisex · mehrere Größen",
    category: "Mode",
    priceCents: 5995,
    unit: "Demo · Partnerfeed offen",
    emoji: "👟",
    tone: "sky",
    verified: false
  },
  {
    id: "zalando-regenjacke",
    shopId: "zalando",
    name: "Leichte Regenjacke",
    subtitle: "wasserdicht · Unisex",
    category: "Mode",
    priceCents: 7995,
    unit: "Demo · Partnerfeed offen",
    emoji: "🧥",
    tone: "leaf",
    verified: false
  }
];

export const getShop = (shopId) => shops.find((shop) => shop.id === shopId);
